### ISSUE TITLE
Generate Python stubs (.pyi)

### ISSUE THREAD

**Issue by miklhh** [apytypes/apytypes#11]
We should consider writing our own Python stubs (`*.pyi`) or automatically generate stubs based on the `*_wrapper.cc` files.

**Comment by oscargus** [comment]
https://github.com/wjakob/nanobind/issues/420

**Comment by miklhh** [comment]
Nanobind v2.0.0 stub generation:
https://nanobind.readthedocs.io/en/latest/typing.html#stubs
