### ISSUE TITLE
Selecting a single item from an array should return a scalar

### ISSUE THREAD

**Issue by oscargus** [apytypes/apytypes#114]
After using APyTypes a bit in practice this is becomes rather annoying. For example, `sum` now returns an array rather than a scalar. Also, `min` and `max` would work if this happened (or comparisons between arrays worked...).

Seems like `variant` is the way to go: https://stackoverflow.com/questions/72846900/function-with-dynamic-return-type-in-pybind11

**Comment by miklhh** [comment]
Scalar variant access for single dimensional arrays and iterators was added in #157 for `APyFixedArray` and in #158 for `APyFloatArray`.

Closed.
