### ISSUE TITLE
Comparisons with int and float (and probably the other APy*-type)

### ISSUE THREAD

**Issue by oscargus** [apytypes/apytypes#16]
https://github.com/apytypes/apytypes/blob/e09260aa4217023ffba7afbf1bbd0d05935bc994/lib/test/test_floating_point.py#L420-L427

https://github.com/apytypes/apytypes/blob/e09260aa4217023ffba7afbf1bbd0d05935bc994/lib/test/apyfixed/test_arithmetic.py#L193-L200

One can probably remove `is_zero`, `is_negative`, etc when this works.

**Comment by miklhh** [comment]
Floating-point comparison support to `APyFixed` was added in b5a37b63b417f097398693235406eaf6259ab602.

**Comment by miklhh** [comment]
Floating-point and integer comparison support to `APyFloat` was added in 1c65c07a6765e8533fb558d8650b966d48ee591e.

**Comment by oscargus** [comment]
Should be OK for now.
