### ISSUE TITLE
ApyFloat division sometimes doesn't quantize to zero when it should

### ISSUE THREAD

**Issue by Theodor-Lindberg** [apytypes/apytypes#188]
Division in APyFloat sometimes quantizes to the smallest subnormal number instead of zero.

This can be reproduced by performing the following operations (that should yield the same result):
```Python
from apytypes import APyFloat
x = APyFloat(sign=0, exp=0, man=1, exp_bits=4, man_bits=3)
y = APyFloat(sign=0, exp=7, man=1, exp_bits=4, man_bits=3)

# APyFloat(sign=0, exp=0, man=1, exp_bits=4, man_bits=3)
x / y

# APyFloat(sign=0, exp=0, man=0, exp_bits=4, man_bits=3)
APyFloat.from_float(float(x) / float(y), exp_bits=4, man_bits=3)
```

**Comment by oscargus** [comment]
One may think that this is correct (and that the from_float-conversion does not round, which I think it should).
