### ISSUE TITLE
Add `leading_fractional_zeros` method to `APyFixed`

### ISSUE THREAD

**Issue by oscargus** [apytypes/apytypes#208]
This method should be replaced with something that directly considers the binary representation:

https://github.com/apytypes/apytypes/blob/5ea5a4632b7dd98ef71526ff83b1602736249592/src/apyfloat.cc#L1153-L1162

**Comment by oscargus** [comment]
Maybe one should also add `larger_than_equal_one` and `larger_than_equal_two` methods to `APyFixed` (C++, not Python) which checks that on a bit level. Should be more efficient that comparing with another fixed-point one and two with all the casting involved.

**Comment by miklhh** [comment]
The following methods were added in #218:

* `APyFixed.leading_zeros() -> int`
* `APyFixed.leading_ones() -> int`
* `APyFixed.leading_signs() -> int`
* `APyFixed.leading_fractional_zeros() -> int`

When replacing `APyFloat::leading_zeros_apyfixed()` with `APyFixed::leading_fractional_zeros`, a single unit test failed in `lib/tests/apyfloat/test_arithmetic.py`. @Theodor-Lindberg promised to have a look at the failing unit test.

**Comment by Theodor-Lindberg** [comment]
@miklhh The failing unit test we looked at yesterday was due to what I believe is a bug in `leading_fractional_zeros`, see issue  #224. However I ended up not using that particular function, so `APyFloat::leading_zeros_apyfixed` has now been updated in PR #223.

**Comment by miklhh** [comment]
@Theodor-Lindberg, good catch, thank you. Fixed in #232. Closed.
