### ISSUE TITLE
Contexts are not concurrent (not thread safe)

### ISSUE THREAD

**Issue by miklhh** [apytypes/apytypes#234]
Having a global context state makes all concurrency of APyTypes non-existent. We must find a new way to handle [Python contexts](https://docs.python.org/3/library/contextlib.html).

It's not that things aren't working at the moment, but we have cornered ourselves and cannot support any type of parallel computing as things are now.

**Comment by Theodor-Lindberg** [comment]
gmpy2 mentions the added support for thread-safe contexts in their 2.1 update, see [here](https://github.com/aleaxit/gmpy). So one can start looking there.

**Comment by miklhh** [comment]
C++ `thread_local` storage duration, read more about it [here on cppreference](https://en.cppreference.com/w/cpp/language/storage_duration).
