### ISSUE TITLE
`pybind11::isinstance<pybind11::int_>()` does not match numpy integers

### ISSUE THREAD

**Issue by miklhh** [apytypes/apytypes#24]
This means that we need to specialize constructors and a-like to accommodate the Numpy data types.

I guess this makes sense since Python integers are arbitrarily long, but Numpy integers are not. I'm not sure whether the same holds for `pybind11:isinstance<pybind11::float_>()` and Numpy floats, but if so, the same specialization has to be done for Numpy floats.

## Minimal example
```Python
>>> import numpy as np
>>> from apytypes import APyFixedArray

>>> APyFixedArray(np.array([3,4,5]), bits=10, int_bits=2)
RuntimeError: Non integer/sequence found when walking integers: 3
```

**Comment by oscargus** [comment]
Can't you just add a case with something like: `pybind11:isinstance<std::int64_t>()`?

The option is to have a constructor with `pybind11::array` and then check the `dtype` of the array.

**Comment by miklhh** [comment]
Constructor support in APyFixed(array) for NumPy integers was added in #163 and constructor support for NumPy floats was added in #164.

From the `xfailed` in `pytest lib/test/apyfloatarray/test_constructors.py`, it looks like this is still an open issue for APyFloats, so I'll leave this open.
