### ISSUE TITLE
Failing floating-point multiplication

### ISSUE THREAD

**Issue by oscargus** [apytypes/apytypes#258]
``` python
x = APyFloat(sign=0, exp=0, man=11, exp_bits=4, man_bits=20)
y = APyFloat(sign=0, exp=5, man=50, exp_bits=16, man_bits=50)
x * y
```
currently returns oo, but should be 0.

**Comment by oscargus** [comment]
I think a reason may be that `normalized` is not correct as sometimes more than one additional exponent bits is required. In this case the resulting exponent in x.normalized() becomes negative, so it ends up to be a gigantic positive number.

**Comment by Theodor-Lindberg** [comment]
I took a quick look at this, and I think you are correct.
