### ISSUE TITLE
Update benchmarks for long floating-point formats

### ISSUE THREAD

**Issue by Theodor-Lindberg** [apytypes/apytypes#278]
After adding a fast path in floating-point addition, PR #274, the long formats happen to fit inside fast path. The benchmarks should therefore be updated to an even longer format in order to use the slow path. Changing from 50 to 60 mantissa bits should be enough. 

The benchmark history might look a bit odd because of this.

**Comment by oscargus** [comment]
This should be enough for addition. Multiplication will still not fit in the fast path.

**Comment by oscargus** [comment]
I did this in an earlier PR.
