### ISSUE TITLE
Broadcasting

### ISSUE THREAD

**Issue by oscargus** [apytypes/apytypes#302]
https://numpy.org/doc/stable/user/basics.broadcasting.html#general-broadcasting-rules (this part we support).

https://numpy.org/doc/stable/user/basics.broadcasting.html#broadcastable-arrays can be added.

**Comment by oscargus** [comment]
A key step to solve this is to implement `broadcast_to` https://numpy.org/doc/stable/reference/generated/numpy.broadcast_to.html

Once that is done, one can simply broadcast one argument to the other size and then use the standard operations. Although this will often be inefficient (as one will have to allocate a new object and copy stuff), it will at least make things work and one can, as a second step, introduce broadcasting rules "locally" in the arithmetic operations to avoid copying etc.

**Comment by miklhh** [comment]
* [`numpy.broadcast_to()`](https://numpy.org/doc/stable/reference/generated/numpy.broadcast_to.html)
* [`numpy.broadcast_arrays()`](https://numpy.org/doc/stable/reference/generated/numpy.broadcast_arrays.html)

**Comment by miklhh** [comment]
### NumPy error on faulty broadcast:
```python
>>> import numpy as np
>>> np.broadcast_to(np.zeros([4,3,2]), (6,2,6,4))
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (4,3,2)  and requested shape (6,2,6,4)
```
