### ISSUE TITLE
Bias conversion

### ISSUE THREAD

**Issue by oscargus** [apytypes/apytypes#322]
The support for mixed-biases are not that well developed, beyond the IEEE-case. I think this is the way to convert general biases.

Two numbers with bias b1 and b2 and exponent bits e1 and e2, converted to e3 exponent bits.

```
b3 = ((b1 + 1)/(2**e1) + (b2 + 1)/(2**e2))*(2**(e3))/2 - 1
``` 
If `e3 >= max(e1, e2)`
```
b3 = ((b1 + 1) << (e3 - e1) + (b2 + 1) << (e3 - e2)) >> 1
```

This should lead to that numbers with IEEE-biases are kept the same and other combinations will get the "average" bias, which is most likely the best we can do. In this case it is rounded downwards, which I think is as good as the other option.

**Comment by Theodor-Lindberg** [comment]
Seems like the second expression should be this?
```Python
((((b1 + 1) << (e3 - e1)) + ((b2 + 1) << (e3 - e2))) >> 1) - 1
```

I think your suggestion makes sense but it can lead to some unexpected results. Consider adding a large number with zero as
```Python
x = APyFloat(sign=0, exp=21, man=0, exp_bits=5, man_bits=2, bias=5)
y = APyFloat(sign=0, exp=0, man=0, exp_bits=5, man_bits=2, bias=25)
# APyFloat(sign=0, exp=31, man=0, exp_bits=5, man_bits=2)
x+y
```
The resulting bias will be $15$ so the exponent of $x$ will be increased by $10$ and thus become infinity.

I think in general one should side with the format representing numbers with greater magnitude, but I'm not sure how that would be formulated. Perhaps something like this:
```Python
b3 = min((b1 + 1) << (e3 - e1), (b2 + 1) << (e3 - e2)) - 1
```

**Comment by oscargus** [comment]
Won't a similar thing happen for small numbers? Adding zero will turn the reault into zero?

**Comment by Theodor-Lindberg** [comment]
Yes that's true.. I think both make sense but in different ways
