### ISSUE TITLE
`to_numpy`-methods

### ISSUE THREAD

**Issue by oscargus** [apytypes/apytypes#35]
It would make sense to add `to_numpy` methods to the array types that returns a proper numpy-array with floats. This will make it possible to plot apytype-arrays in Matplotlib.

One may also consider adding a method (or an argument to `to_numpy`)  that returns a numpy-array with APyXXX-objects (which maybe is useful in some situations).

Finally, one may also consider some method/argument that returns and array of (numpy)-ints corresponding to `to_bits`.

**Comment by miklhh** [comment]
`APyFixedArray.to_numpy()` was added in #56.

**Comment by Theodor-Lindberg** [comment]
`APyFloatArray.to_numpy()` was added in  #79.

**Comment by oscargus** [comment]
I think these are the two that we can foresee currently?
