### ISSUE TITLE
Rewrite float-array addition/subtraction to use a single function

### ISSUE THREAD

**Issue by oscargus** [apytypes/apytypes#404]
Currently, subtraction is done as https://github.com/apytypes/apytypes/blob/5055aa33857ba29afecbfc8551f9db6a9b125b35/src/apyfloatarray.cc#L454

However, this causes a copy of the array and therefore a performance penalty for subtraction compared to addition, see top plot below.

It would be useful to have a single method called with a bool for add or subtract to alleviate this.

![image](https://github.com/apytypes/apytypes/assets/8114497/beb9ba3f-9631-441a-b501-19585704af22)

**Comment by miklhh** [comment]
This issue is fixed with #574.
