### ISSUE TITLE
Dedicated `sum` method for array clases?

### ISSUE THREAD

**Issue by Theodor-Lindberg** [apytypes/apytypes#443]
Right now one can do `sum(arr)` on an array, which is convenient. However this doesn't respect the accumulator context, should there perhaps also exist a dedicated `.sum()` method for the array classes which does use the accumulator context?

On a related topic. An interesting feature for `APyFloatArray` would perhaps be a summation method which performs the summation in a sorted order (as it would increase the precision). This is quite an expensive operation for systems to implement, so this feature is probably more interesting than useful.

**Comment by oscargus** [comment]
Not sure accumulator context is the main reason (here it is easy to cast before and after, as opposed to matrix multiplication), but there are many other reasons. This is actually one of the methods in #303.

**Comment by Theodor-Lindberg** [comment]
Oh yes, then its covered by that issue and we can close this.

The method for a sorted sum for `APyFloatArray` could perhaps be its own issue, with low priority that someone could do if they have time and feel like it. Although one could implement it by hand, so maybe not worthy of its own method?

The accumulator context here is mostly for convenience, since it's easy to get around it like you say. The one, although perhaps not common, case that is difficult without accumulator context would be if someone would like to sum floating-point numbers using a lower-precision accumulator and avoid double rounding.

**Comment by oscargus** [comment]
Implemented in #473
