### ISSUE TITLE
Doc: incorrect link to development on main page

### ISSUE THREAD

**Issue by oscargus** [apytypes/apytypes#461]
For some reason it selects the Python Development Tools info: https://docs.python.org/3/library/development.html#development

Correct link: https://apytypes.github.io/apytypes/development.html

**Comment by miklhh** [comment]
Are you referring to the Development page in the side panel (content menu) of the APyTypes documentation webpage? For me, that development link leads to our development page https://apytypes.github.io/apytypes/development.html, like it should do.

**Comment by oscargus** [comment]
No, the link in:

"Or look at the [Development Tools](https://docs.python.org/3/library/development.html#development) instructions."

on the main/first page.
