### ISSUE TITLE
`_is_positive` not giving correct result

### ISSUE THREAD

**Issue by Theodor-Lindberg** [apytypes/apytypes#514]
`_is_positive` is returning `False` on a positive number.

Example:
```Python
from apytypes import APyFixed
x = APyFixed(1, int_bits=1, frac_bits=1080)
x._is_positive # False
x._is_negative # False
x.is_zero # False

x > 0 # True
x < 0 # False
x == 0 # False
```
I'm not sure if `_is_positive` and `_is_negative` should be accessible from the Python API to begin with, from what I remember we decided to remove it as it can be replaced by comparisons against zero. However I stumbled upon this when I tried to use the corresponding C++ function.

**Comment by oscargus** [comment]
Private method, so not documented what it does. But probably makes sense that the corresponding C++-function works as one may guess...
