### ISSUE TITLE
Use better exception messages

### ISSUE THREAD

**Issue by miklhh** [apytypes/apytypes#60]
Find all instances of `throw std::` in
* apyfixed.cc
* apyfixed.h
* apyfixedarray.cc
* apyfixedarray.h,

make sure that the exception messages give proper information when raised. It should be simple now that Fmt has been added to the project.

**Comment by oscargus** [comment]
One should also consider throwing more targeted error. `TypeError` and `ValueError` in particular.

**Comment by miklhh** [comment]
For APyFixedArray:
* Proper exception messages added in 3d12f908e02b0c9ae6ba733cdb90556b7aad4eab
* Proper (NumPy equivalent) exception types added in f74ba35a13d6da9f2dcc1b7863f77298cbc90fbd

**Comment by miklhh** [comment]
With the addition of `fmt::format()` it is now very easy to throw good error messages, and this should be done for all raised exceptions.

However, it does not make sense to have such a broad issue as this one open. For more targeted 'better exception message' issues, please open a new issue.

Closed.
