### ISSUE TITLE
Add `__radd__` and `__rmul__` methods for ints

### ISSUE THREAD

**Issue by oscargus** [apytypes/apytypes#63]
If nothing else, these should check if the int argument is zero and in that case return the other object (can raise for other integer values). This is required for `sum` and `prod` which adds with 0 the first time.

**Comment by miklhh** [comment]
Placeholder (only supports zero integers) left- and right-arithmetic methods for APyFixed were added in 18f11dd.

**Comment by oscargus** [comment]
Similar for `APyFixedArray` was added in #73.

**Comment by Theodor-Lindberg** [comment]
Similar for `APyFloatArray` was added in  #79.

**Comment by oscargus** [comment]
Added for `APyFloat`.
