### ISSUE TITLE
Migrate C++ unit tests to Python

### ISSUE THREAD

**Issue by miklhh** [apytypes/apytypes#8]

**Comment by oscargus** [comment]
No, *only* use Python unit tests.

**Comment by miklhh** [comment]
More tests are continually being added. The Makefile and the make-based unit tests where completely removed in 261fa2d. I consider this issue finished as the C++ unit tests have been migrated to Pytest. We should consider doing more tests using Pytest though, the coverage is currently rather low. 

Closed by #9
