### ISSUE TITLE
`resize` method naming convention

### ISSUE THREAD

**Issue by miklhh** [apytypes/apytypes#96]
The current `resize` method of scalar and array types returns a new object with the same stored value(s), under a new word length. The method [`numpy.ndarray.resize`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.resize.html) is used to change the `shape` of an numpy array-type object. We might consider changing the name of the bit-resizing method to something else, not to confuse it with the shape-resizing method. This also makes sense as we intend to add support for shape-resizing methods of our array types in the near future.

I suggest `bit_resize` for the bit-resizing method.

**Comment by oscargus** [comment]
I see the potential clash (and maybe we would like to add resize later), but I think we should have a short and simple word for this. What about `cast`?

**Comment by miklhh** [comment]
Short and simple names are good. I believe `cast` is a decent candidate, it's both short and clear.

**Comment by Theodor-Lindberg** [comment]
Sound good. As we already have similarities to numpy it might cause confusions having the same function name but with different behaviour, like you say.

(So the renaming for APyFloat becomes `cast_to` $\rightarrow$ `resize` $\rightarrow$ `cast` heh)

**Comment by oscargus** [comment]
We should probably deprecate `resize` for a bit (but still support it so that reviewers of the ARITH paper can run the code as described).

See https://stackoverflow.com/questions/62465062/best-way-to-mark-a-pybind11-binding-as-deprecated
